-- liquibase formatted sql

-- changeset skorobeynikova:1



CREATE TABLE notification_task_name
(
    id                     BIGINT generated by default as identity primary key,
    message                TEXT      NOT NULL,
    user_id                BIGINT    NOT NULL,
    notification_date_time TIMESTAMP NOT NULL
);